### ISSUE TITLE
[BUG] The session is lost inexplicably

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-sdk-web-wasm#106]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

IM初始化后有 `get_all_conversations` 请求会有五个会话，但是实际我在请求 `getConversationListSplit` 的结果只有3个会话，以下是完整日志：

(数据太大 https://gist.github.com/cipchk/79446ccfe62dd75131bc1882e20032fc )

> 另把本地 indexeddb 数据库删除，再次刷新网页得到的会话列表就对了。

**Comment by Bloomingg** [comment]
https://github.com/openimsdk/open-im-sdk-web-wasm/blob/main/assets/wasm_exec.js#L22
The SDK core logs will be printed here.
