### ISSUE TITLE
[BUG] vue2 webpack4.x An exception occurred during the installation of the latest SDK version as instructed

### ISSUE THREAD

**Issue by 15949634581** [openimsdk/open-im-sdk-web-wasm#110]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

![企业微信截图_17228262975782](https://github.com/user-attachments/assets/94914420-5800-4eef-ab95-a585b6ed1de4)
3.5.1 is fine, but the latest SDK will report this exception

**Comment by Bloomingg** [comment]
Are you deploying on an https site?

**Comment by 15949634581** [comment]
I am only running the client locally, whereas the server is being deployed on an HTTPS site
