### ISSUE TITLE
[BUG] 3.8 getGroupMemberList throws an exception when `filter` is `0`

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-sdk-web-wasm#112]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

使用 `@openim/wasm-client-sdk:3.8.1` 类库。

以下是相关日志，很容易复现：

```
_message.service.ts:42 getMemberFailed 
{operationID: '64c01309-503f-44e2-ab75-19364a84b780', event: 'Getgroupmemberlist', errCode: 10002, errMsg: '10002 ArgsError'}
```

这一问题与 https://github.com/openimsdk/open-im-sdk-flutter/issues/146 一样。

**Comment by lgz5689** [comment]
After upgrading the sdk version, you need to repeat the following steps：
Locate the @openim/wasm-client-sdk subdirectory in the node_modules directory of your project. Copy all the files in the assets folder to your project's public resource directory.
