### ISSUE TITLE
[FEATURE REQUEST]  When developing with TypeScript, the entity type is not exported for developers to use.

### ISSUE THREAD

**Issue by afeibukaixin** [openimsdk/open-im-sdk-web-wasm#117]
### Why this feature?

During the development process, developers often need to reference its type, which facilitates more efficient development.
<img width="442" alt="iShot_2024-08-16_11 56 41" src="https://github.com/user-attachments/assets/9f18ab0e-c447-4a97-b042-cd27f3cc6fb2">

### Suggested Solution

Add this line of code in the import file.
<img width="758" alt="iShot_2024-08-16_11 53 47" src="https://github.com/user-attachments/assets/28f7b86e-4aee-4fb7-b908-6fb3570bff7a">

**Comment by Bloomingg** [comment]
will be added in the next version
