### ISSUE TITLE
[BUG] umi.js3.5 initWorker failure

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-web-wasm#118]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

<img width="854" alt="截屏2024-08-20 18 41 11" src="https://github.com/user-attachments/assets/7b0602da-b61a-44a0-b0ef-6e27ecd84e74">
<img width="966" alt="截屏2024-08-20 18 42 58" src="https://github.com/user-attachments/assets/8403bdf2-1784-4e9f-92a4-34f660bac7e2">

**Comment by OrrinHatch** [comment]
<img width="415" alt="截屏2024-08-20 18 44 23" src="https://github.com/user-attachments/assets/80016f95-d8a4-4982-8d61-7584a7bd4ce3">
the webpack5 and workerLoader have been started
[umi.js 3.5 文档](https://v3.umijs.org/zh-CN/config#webpack5)

**Comment by OrrinHatch** [comment]
<img width="799" alt="截屏2024-08-20 21 19 25" src="https://github.com/user-attachments/assets/528cc05f-07b5-4136-8493-2bfdbf9d5a15">
7296345ad6d9901d2822.js 
file content:
```
export default function Worker_fn() {
  return new Worker(__webpack_public_path__ + "worker.worker.js");
}
```
worker.worker.js
file content:
<img width="1482" alt="截屏2024-08-20 21 21 35" src="https://github.com/user-attachments/assets/bc75db79-0bb9-44c6-9e0e-068e718c1a1b">

**Comment by OrrinHatch** [comment]
> ### OpenIM Server Version
> 3.8.0
> 
> ### Operating System and CPU Architecture
> macOS (ARM)
> 
> ### Deployment Method
> Docker Deployment
> 
> ### Bug Description and Steps to Reproduce
> <img alt="截屏2024-08-20 18 41 11" width="854" src="https://private-user-images.githubusercontent.com/99718299/359444698-7b0602da-b61a-44a0-b0ef-6e27ecd84e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjA0NjEsIm5iZiI6MTcyNDE2MDE2MSwicGF0aCI6Ii85OTcxODI5OS8zNTk0NDQ2OTgtN2IwNjAyZGEtYjYxYS00NGEwLWIwZWYtNmUyN2VjZDg0ZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEzMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDUwNTY4NzczYmVmYTdkNWY5ZjVkMGJkMWI1M2FlNTIzNzQxZGIxNWY4NjA5ZTJhNDA3ZjI2MTVlY2ViN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pqMHxj8PDzvguMzgAql5u375BuBuJFGInUcdpU39xA"> <img alt="截屏2024-08-20 18 42 58" width="966" src="https://private-user-images.githubusercontent.com/99718299/359445215-8403bdf2-1784-4e9f-92a4-34f660bac7e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjA0NjEsIm5iZiI6MTcyNDE2MDE2MSwicGF0aCI6Ii85OTcxODI5OS8zNTk0NDUyMTUtODQwM2JkZjItMTc4NC00ZTlmLTkyYTQtMzRmNjYwYmFjN2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEzMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNzIxNmY1NTVlODVhZTJmZWExZDFmYWUxMTI5ZTY1ODg5MWJjOTMxMTRhN2JmNjAxM2FiZTcxMzY0ZjU0NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0xjetDr46AOVfMVBquf9A_ZmfkZPWeeeapXXU8gKIIk">
> ### Screenshots Link
> _No response_

For this problem, I need to close mfsu

**Comment by OrrinHatch** [comment]
![WechatIMG1007](https://github.com/user-attachments/assets/67e40e5c-6712-4257-9ba6-6caa63d42212)
workerPromise was not executed in this line

**Comment by Bloomingg** [comment]
Maybe you got a wrong address when loading the webworker

**Comment by OrrinHatch** [comment]
The issue has been resolved after upgrading to the latest version of Umi.
