### ISSUE TITLE
[BUG]  MainContentLayout-868bfdc8.js:1 TypeError: window.commonEventFunc is not a function     at We.login (open-im-sdk-wasm-3b339908.js:1:25495)     

### ISSUE THREAD

**Issue by wang22290** [openimsdk/open-im-sdk-web-wasm#128]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

![image](https://github.com/user-attachments/assets/78a25b8a-5f33-4b0c-b2f5-f714c18ac731)

I’m using an Electron demo that references open-im-sdk-web-wasm 3.8.0. When running the project with npm run dev, no errors occur. However, after packaging the project into a .app file, I get the following error: TypeError: window.commonEventFunc is not a function at We.login (open-im-sdk-wasm-3b339908.js:1:25495), and I’m unable to log in to IMSDK.”

**Comment by Bloomingg** [comment]
Did you move the openIM.wasm file?

**Comment by wang22290** [comment]
> Did you move the openIM.wasm file?

No ,I am using an Electron demo and using Electron Forge to package the project without changing any code.

**Comment by Bloomingg** [comment]
So you are not using the official demo, maybe you can refer to the official electon demo. Your problem is because the openIM.wasm file is not loaded correctly.

**Comment by wang22290** [comment]
> So you are not using the official demo, maybe you can refer to the official electon demo. Your problem is because the openIM.wasm file is not loaded correctly.



>I didn't understand what you meant. I used the Electron Demo on GitHub, but I just packaged it into an. app file using the Electron Forge tool and installed it on my Mac computer,

<img width="579" alt="image" src="https://github.com/user-attachments/assets/2870bfbc-dc30-4085-bbd3-7cea3eb717ee">

**Comment by Bloomingg** [comment]
You need to make sure that the packaged file can still be loaded correctly into the wasm file. In fact, the dev and prod environments are somewhat different. For example, the [following processing](https://github.com/openimsdk/openim-electron-demo/blob/main/src/layout/MainContentWrap.tsx#L13) is done in `openim-electron-demo`. You may need to check your actual import path.

**Comment by wang22290** [comment]
> You need to make sure that the packaged file can still be loaded correctly into the wasm file. In fact, the dev and prod environments are somewhat different. For example, the [following processing](https://github.com/openimsdk/openim-electron-demo/blob/main/src/layout/MainContentWrap.tsx#L13) is done in `openim-electron-demo`. You may need to check your actual import path.

I modified the path as you suggested, but still reported the same error,
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/16cd04cd-f5e4-40bc-adac-9cec2f499bd0">

**Comment by Bloomingg** [comment]
actually, I don’t mean to ask you to change the path to the same path as mine… Because the basic framework structure of your project may not be the same as the demo, the key point is how to find the correct import path that belongs to your project structure.

**Comment by wang22290** [comment]
> actually, I don’t mean to ask you to change the path to the same path as mine… Because the basic framework structure of your project may not be the same as the demo, the key point is how to find the correct import path that belongs to your project structure.

I have discovered another issue where the openIMwasm file in the dist file generated by my build cannot be properly packaged into the. app project, as shown in the picture. I have tried to modify the packaging configuration, but it still does not take effect
<img width="544" alt="image" src="https://github.com/user-attachments/assets/4965cb86-aaff-4f63-9f2b-f08d3a0a7dc5">

<img width="684" alt="image" src="https://github.com/user-attachments/assets/7f47cb7c-d7c6-4f4e-974e-7fbdfa9ac3e1">

![image](https://github.com/user-attachments/assets/534ed071-df93-47b7-a334-5ad8ff5d0172)

**Comment by PineSongCN** [comment]
我这边是网页版报了类似的错误，原因是nginx的mine.types缺少wasm的类型，没有正确识别解析wasm文件导致的。
https://juejin.cn/post/7410710728783298611

**Comment by wang22290** [comment]
> actually, I don’t mean to ask you to change the path to the same path as mine… Because the basic framework structure of your project may not be the same as the demo, the key point is how to find the correct import path that belongs to your project structure.

@Bloomingg 

I modified the package directory of openIM.wasm. I can get the correct address directly under the Resources file, but window.commonEventFunc is not a function still exists.

I found that Electron may have file path problems, especially in production environments, where file:// protocol paths cannot be loaded directly using the browser environment.

Is this error related to this?

![image](https://github.com/user-attachments/assets/0cbd7f3f-d459-4c24-81d7-eea82e18b375)
![image](https://github.com/user-attachments/assets/7fe2039d-ce75-4e19-9a72-a775a696574a)

**Comment by Bloomingg** [comment]
you can update you sdk and try again.
```bash
npm i @openim/wasm-client-sdk@latest
```

**Comment by wang22290** [comment]
> you can update you sdk and try again.
> 
> ```shell
> npm i @openim/wasm-client-sdk@latest
> ```

@Bloomingg 

I used the latest version of openIMSDK ("@openim/wasm-client-sdk": "^3.8.1",) and the Electron Demo from github, and packaged it into an app file with Electron Forge, but still got an error.

![image](https://github.com/user-attachments/assets/f58a4a3c-147d-4ffb-ab44-af1a4e840e67)

**Comment by wang22290** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> I reported a similar error on the web version. The reason is that nginx's mine.types lacks the wasm type and does not correctly identify and parse the wasm file. https://juejin.cn/post/7410710728783298611

我使用的是Electron Demo。我没有理解这个配置该如何修改
