### ISSUE TITLE
[BUG] No friends, error will be reported when initializing the browser console

### ISSUE THREAD

**Issue by cookTanxin** [openimsdk/open-im-sdk-web-wasm#135]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Windows (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

初始化在没有好友，登录，调用IMSDK.login,控制台会报错，但是刷新浏览器以后不会报错，调用其他方法都是正常的，
<img width="1433" alt="iShot_2024-09-28_08 51 48" src="https://github.com/user-attachments/assets/d74a158e-1e2d-4a1f-ad50-43a6397ec9b6">
<img width="975" alt="iShot_2024-09-28_08 10 40" src="https://github.com/user-attachments/assets/6bebadf2-015f-4cea-a285-c667e404811a">

**Comment by Bloomingg** [comment]
This error has no impact and can be ignored.
