### ISSUE TITLE
[BUG] Picture and video upload issues

### ISSUE THREAD

**Issue by lgq1212** [openimsdk/open-im-sdk-web-wasm#138]
### OpenIM Server Version

3.6

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

前端文件通过原有方式上传，
因为跨域和访问问题将external_ip:1085 改成了 192.168.0.31:10083 通过nginx代理到了1085端口

### Screenshots Link

![81729505970_ pic](https://github.com/user-attachments/assets/ea3c3dca-36f4-4cab-97c2-ee2df8ce8b17)

**Comment by Bloomingg** [comment]
It's a normal phenomenon. Will not affect client access.
