### ISSUE TITLE
[BUG] createVideoMessageByURL not return build message body

### ISSUE THREAD

**Issue by c1184405532** [openimsdk/open-im-sdk-web-wasm#139]
### OpenIM Server Version

"@openim/wasm-client-sdk": "^3.8.2-1"

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

I want to build send video file messages, The official documentation let me use createFileMessageByURL, but I had problems building the message body, There is no video information in the returned message body

I then choose to use createVideoMessageByURL, but it simply returns an empty message body

### Screenshots Link

![image](https://github.com/user-attachments/assets/ba45c0ae-0939-4b39-971e-820ec4c86773)
![image](https://github.com/user-attachments/assets/ec2d38be-dce3-4553-b636-2126d7df9589)
![image](https://github.com/user-attachments/assets/a433c839-87d3-48ff-885a-ea344be11041)
![image](https://github.com/user-attachments/assets/e772525c-4c99-4c29-8108-d34265f30b7f)

**Comment by Bloomingg** [comment]
传入的`duration`字段必须是一个整数

**Comment by c1184405532** [comment]
> The `duration` field passed in must be an integer.
ok i got it .

i use messageItem.duration = Math.ceil(duration) ，current no problem
