### ISSUE TITLE
[BUG] createQuoteMessage cannot be return build message data

### ISSUE THREAD

**Issue by c1184405532** [openimsdk/open-im-sdk-web-wasm#141]
### OpenIM Server Version

"@openim/wasm-client-sdk": "^3.8.2-1"

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

i use createQuoteMessage but cannot be return data
this is my code 
const buildMessageBody = await IMSDK.createQuoteMessage({ text, message }, getOpenImOerationID())

### Screenshots Link

![企业微信截图_17314820946908](https://github.com/user-attachments/assets/0a9560f6-1e59-412f-9ee7-3f27d1498000)

![企业微信截图_17314821443959](https://github.com/user-attachments/assets/cbc3090a-c466-4cbb-9d1e-35100bfb5b76)

**Comment by Bloomingg** [comment]
You can first convert the message to a string and pass it in. This problem will be fixed in the next version.

**Comment by c1184405532** [comment]
> You can first convert the message to a string and pass it in. This problem will be fixed in the next version.

Yes, I understand，But I want to use the following methods，Is this definition correct?

```
const buildMessageBody = await IMSDK.createQuoteMessage({ text, message }, getOpenImOerationID())

// SDK构建消息失败, 手动通过其他api构建引用消息体
if (!buildMessageBody.data) {
  const fileBaseInfo = { filePath: '', fileName: '', uuid: '', sourceUrl: '', fileSize: 0, fileType: '' }
  const newMessageBody = await IMSDK.createFileMessageByURL(fileBaseInfo, getOpenImOerationID())
  console.log('createQuoteMessage构建消息体失败, 手动构建消息体：', newMessageBody)

  buildMessageBody.data = {
    ...newMessageBody.data,
    fileElem: {},
    contentType: 114, // 引用消息类型
    quoteElem: { text, quoteMessage: message }
  }
}
```

**Comment by Bloomingg** [comment]
It is not recommended to manually construct the message body. Any error in a field will lead to the failure of message sending.

**Comment by c1184405532** [comment]
> It is not recommended to manually construct the message body. Any error in a field will lead to the failure of message sending.

ok, I will be use String params pass it in 

```
if (!buildMessageBody.data) {
  const newMessageBody = await IMSDK.createQuoteMessage({ text, message: JSON.stringify(message) }, getOpenImOerationID())
  buildMessageBody.data = newMessageBody.data
}
```
