### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by fts11259375** [openimsdk/open-im-sdk-web-wasm#144]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

项目从3.6.x更新到3.8.2后，web端登录之后无法获取登录用户，调用一些方法也会报错，下面的截图是流程极度简化后的报错，只在OnConnectSuccess回调之后调用了getLoginUserID

### Screenshots Link

![QQ20241128-122654](https://github.com/user-attachments/assets/0b0eb9fb-fd04-46be-9323-b4fb87161b7b)
![QQ20241128-123329](https://github.com/user-attachments/assets/34dd1d37-6c0c-412d-9ae5-7df79bdb26d0)

**Comment by fts11259375** [comment]
刚试了下，我把public的那3个文件替换成3.6.x的就正常

**Comment by Bloomingg** [comment]
Fixed in v3.8.2-3
