### ISSUE TITLE
[BUG] It can not createMessage

### ISSUE THREAD

**Issue by timothyzhao0507** [openimsdk/open-im-sdk-web-wasm#148]
### OpenIM Server Version

Server: 3.8.1, Web: 3.8.2

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

I use Quasar+Vite+VUE to develop the Web IM following documents.
But it report errors when createTextMessage. My Code:

`
import {onBeforeMount, reactive, ref} from "vue";
import {Notify, useMeta} from "quasar";
import {CbEvents, getSDK} from "@openim/wasm-client-sdk";
import {CURRENT_USER, IM_TOKEN, ImApi, ImWs} from "src/js/Constants.js";
import Message from "src/js/Message.js";

defineOptions({
  name: 'Chat'
});
useMeta({
  title: 'Chatting'
});

const IMSDK = getSDK({
  coreWasmPath: "/openIM.wasm",
  sqlWasmPath: "/sql-wasm.wasm",
  debug: true, //Debug日志
});

IMSDK.on(CbEvents.OnRecvNewMessages, ({data: messages}) => {
  console.log(messages);
  Notify.create({
    type: 'positive',
    message: messages
  });
});

const CurrUser = reactive(JSON.parse(sessionStorage.getItem(CURRENT_USER)));
const ImToken = sessionStorage.getItem(IM_TOKEN);
const loading = ref(false);
const message = reactive(new Message());
message.msg = "Hello IM";
// console.log(CurrUser.id, CurrUser.username); //TODO:user

const onSendMsg = async () => {
  loading.value = true;
  const msg = await IMSDK.createTextMessage("Hello OpenIM");
  console.log("TextMessage",msg); //TODO:TextMessage
  await IMSDK.sendMessage({
    recvID: "member", //TODO:接收方ID
    groupID: "",
    message: msg.data
  }).then(res => {
    console.log("sent", res);
  }).catch((code, msg) => {
    console.error(code, msg);
  });
  loading.value = false;
};

IMSDK.on(CbEvents.OnConnecting, () => {
  console.log("Connecting...");
});
IMSDK.on(CbEvents.OnConnectSuccess, () => {
  console.log("Connected");
});
IMSDK.on(CbEvents.OnConnectFailed, () => {
  console.log("Connect Failed");
});
IMSDK.on(CbEvents.OnUserTokenExpired, () => {
  console.log("User Token Expired ...");
});

onBeforeMount(async () => {
  console.log("准备登录",ImApi, ImWs); //TODO:准备登录
  await IMSDK.login({
    userID: CurrUser.id, //IM userID
    token: ImToken, //IM User Token
    apiAddr: ImApi, //IM API 地址，一般为`http://domain:10002`
    wsAddr: ImWs, //IM WS 地址，一般为`ws://domain:10001`
    platformID: 5 //当前登录平台号(Web端为5)
  }).then((res) => {
    console.log("success", res);
  }).catch(({code, msg}) => {
    console.error(code, msg);
  });
  console.log("登录完成",ImApi, ImWs); //TODO:登录完成
});
`

### Screenshots Link

![Console](https://github.com/user-attachments/assets/2de6bf4e-fb8c-4437-a6ed-61d6eb10ed9e)

**Comment by Bloomingg** [comment]
According to the log, you called other APIs before logging in successfully. You should synchronously wait for the return of login and confirm that you have received the [onConnectSuccess](https://docs.openim.io/zh-Hans/sdks/callback/onConnectSuccess) callback.

**Comment by timothyzhao0507** [comment]
> According to the log, you called other APIs before logging in successfully. You should synchronously wait for the return of login and confirm that you have received the [onConnectSuccess](https://docs.openim.io/zh-Hans/sdks/callback/onConnectSuccess) callback.

But where is the wrong according to my code? Can you help me to resolve the problem, It perplexed me so long time.

**Comment by timothyzhao0507** [comment]
`<template>
  <q-page>
    <q-form class="q-gutter-md" method="post" action="#" @submit.prevent="onSendMsg" @reset="reset()">
      <q-input type="text" name="msg" v-model="message.msg" label="消息" maxlength="1000" aria-required="true" no-error-icon>
        <template #prepend>
          <q-icon name="chat"/>
        </template>
      </q-input>
      <q-stepper-navigation>
        <q-btn type="submit" color="primary" :loading="loading">发送</q-btn>
      </q-stepper-navigation>
    </q-form>
  </q-page>
</template>

<script setup>
import {onBeforeMount, reactive, ref} from "vue";
import {Notify, useMeta} from "quasar";
import {CbEvents, getSDK} from "@openim/wasm-client-sdk";
import {CURRENT_USER, IM_TOKEN, ImApi, ImWs} from "src/js/Constants.js";
import Message from "src/js/Message.js";

defineOptions({
  name: 'Chat'
});
useMeta({
  title: 'Chatting'
});

const IMSDK = getSDK({
  coreWasmPath: "/openIM.wasm",
  sqlWasmPath: "/sql-wasm.wasm",
  debug: true, //Debug日志
});

IMSDK.on(CbEvents.OnRecvNewMessages, ({data: messages}) => {
  console.log(messages);
  Notify.create({
    type: 'positive',
    message: messages
  });
});

const CurrUser = reactive(JSON.parse(sessionStorage.getItem(CURRENT_USER)));
const ImToken = sessionStorage.getItem(IM_TOKEN);
const loading = ref(false);
const message = reactive(new Message());
message.msg = "Hello IM";
// console.log(CurrUser.id, CurrUser.username); //TODO:user

const onSendMsg = async () => {
  loading.value = true;
  const msg = await IMSDK.createTextMessage("Hello OpenIM");
  console.log("TextMessage",msg); //TODO:TextMessage
  await IMSDK.sendMessage({
    recvID: "member", //TODO:接收方ID
    groupID: "",
    message: msg.data
  }).then(res => {
    console.log("sent", res);
  }).catch((code, msg) => {
    console.error(code, msg);
  });
  loading.value = false;
};

IMSDK.on(CbEvents.OnConnecting, () => {
  console.log("Connecting...");
});
IMSDK.on(CbEvents.OnConnectSuccess, () => {
  console.log("Connected");
});
IMSDK.on(CbEvents.OnConnectFailed, () => {
  console.log("Connect Failed");
});
IMSDK.on(CbEvents.OnUserTokenExpired, () => {
  console.log("User Token Expired ...");
});

onBeforeMount(async () => {
  console.log("准备登录",ImApi, ImWs); //TODO:准备登录
  await IMSDK.login({
    userID: CurrUser.id, //IM userID
    token: ImToken, //IM User Token
    apiAddr: ImApi, //IM API 地址，一般为`http://domain:10002`
    wsAddr: ImWs, //IM WS 地址，一般为`ws://domain:10001`
    platformID: 5 //当前登录平台号(Web端为5)
  }).then((res) => {
    console.log("success", res);
  }).catch(({code, msg}) => {
    console.error(code, msg);
  });
  console.log("登录完成",ImApi, ImWs); //TODO:登录完成
});

</script>

<style scoped>

</style>
`

**Comment by timothyzhao0507** [comment]
![network_list](https://github.com/user-attachments/assets/acc485ce-935b-47fd-a490-a4c3c02ad002)

I just find It have a file named "worker.js" can not load. Whether it is related to this? how to resolve it?

**Comment by timothyzhao0507** [comment]
This my project package.
[im_web.zip](https://github.com/user-attachments/files/18228126/im_web.zip)

**Comment by Bloomingg** [comment]
add quasar support in v3.8.2-4

**Comment by timothyzhao0507** [comment]
> add quasar support in v3.8.2-4

Thank you very much!

It is works.
