### ISSUE TITLE
[Other]: Do you have an SDK version that supports server version 3.6?

### ISSUE THREAD

**Issue by buhuia** [openimsdk/open-im-sdk-web-wasm#156]
<img width="333" alt="image" src="https://github.com/user-attachments/assets/55b53e59-ae24-451a-9c24-37b128c76347" />

I noticed that the minimum version of this SDK is 3.8, while our server version is lower at 3.6. The Flutter SDK on our side is 3.5.1. Is there a WASM SDK similar to version 3.5.1? When integrating, I found that some interfaces are working while others are throwing errors. Overall, it seems that the 3.8.2 SDK doesn't work well with the 3.6 server. Besides upgrading the server, are there any other solutions?

**Comment by Bloomingg** [comment]
The suggestion is to uniformly upgrade to the latest version (3.8.2). If you really need to use an old version, you can try installing (npm i open-im-sdk-wasm@3.5.3-alpha.7).

**Comment by Bloomingg** [comment]
You can directly view the API list and parameters in the Type script type file description of the corresponding version.

**Comment by buhuia** [comment]
OK，its work for me。thanks

**Comment by buhuia** [comment]
This issue has been resolved。
