### ISSUE TITLE
Does it support mini-programs? The maximum size for a mini-program package is 2MB. Can this package, which is 5MB, be resolved?

### ISSUE THREAD

**Issue by social-uni** [openimsdk/open-im-sdk-web-wasm#41]

**Comment by ZowieTao** [comment]
可以的，目前这个包中是有一个默认的sdk-core导出的wasm资源文件所以大小会比较大

**Comment by social-uni** [comment]
> 

您好， 能否具体说下， 如何解决 小程序包2m，这个库5m的问题

**Comment by social-uni** [comment]
> 可以的，目前这个包中是有一个默认的sdk-core导出的wasm资源文件所以大小会比较大

您好， 能否具体说下， 如何解决小程序主包最大允许2m，这个库5m的问题嘛

**Comment by Overclockers** [comment]
感觉不支持，里面会用到indexeddb的内容，小程序没window对象，除非你搞H5，然后小程序嵌套webview

**Comment by ZowieTao** [comment]
这个包里面assets里面的main.wasm 作为一个兜底wasm资源，可以fork出来删掉后重新build，运行sdk时传入远端的wasm资源地址应该是可以改善大小的问题，然后关于使用到indexdb来实现db能力的话可以根据具体环境来使用其他方案做这个

**Comment by Bloomingg** [comment]
You can use the pure JavaScript SDK for mini programs in the v3 version.https://github.com/openimsdk/open-im-sdk-web
