### ISSUE TITLE
Bug: Using UniApp or Vue to package SDK is an error

### ISSUE THREAD

**Issue by bleasprodhnf** [openimsdk/open-im-sdk-web-wasm#51]
### What happened?

![image](https://github.com/OpenIMSDK/Open-IM-SDK-Web-Wasm/assets/88301633/3f050856-4528-4dfe-a069-68a30c7cb34d)

### What did you expect to happen?

How to fix this error

### How can we reproduce it (as minimally and precisely as possible)?

Using UniApp or Vue to package SDK is an error

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by snakebenjm** [comment]
Bro, I got the same problem, At first I was prompted with Go undefined, I fixed it but it gave me this

**Comment by Bloomingg** [comment]
Please provide the address of the code warehouse that can reproduce the problem. In addition, for uni-app, the introduction of wasm sdk is currently not supported.

**Comment by bleasprodhnf** [comment]
This error occurs when vue2+webpack imports wasm directly

**Comment by Bloomingg** [comment]
#72
