### ISSUE TITLE
Bug: This error occurs when vue2+webpack imports wasm directly

### ISSUE THREAD

**Issue by bleasprodhnf** [openimsdk/open-im-sdk-web-wasm#52]
### What happened?

![image](https://github.com/OpenIMSDK/Open-IM-SDK-Web-Wasm/assets/88301633/e43f1dac-c969-4d68-a51f-9ec5ec3e495d)

### What did you expect to happen?

Fix the problem

### How can we reproduce it (as minimally and precisely as possible)?

This error occurs when vue2+webpack imports js-sdk-wasm directly,not js-sdk-web-wasm

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools
The project address of the test
https://github.com/bleasprodhnf/vue2
<details>
</details>

**Comment by bleasprodhnf** [comment]
https://github.com/bleasprodhnf/vue2 
The project address of the test

**Comment by Bloomingg** [comment]
#72
