### ISSUE TITLE
[Other]: There is a problem with getAllConversationList. When you log out, you get the session of the previous account.

### ISSUE THREAD

**Issue by liangxiaobo** [OpenIMSDK/Open-IM-SDK-Web-Wasm#58]
### What would you like to share?

Log out of account A in the browser, and log in to account B. At this time, im.getAllConversationList() gets the local conversation list data of account A and account B, and the browser must be refreshed to make it normal

**Comment by Bloomingg** [comment]
fixed in v3.1.0
