### ISSUE TITLE
Bug: Bidirectional messages are not interoperable.

### ISSUE THREAD

**Issue by QNV5** [openimsdk/open-im-sdk-web-wasm#63]
### What happened?

In the same session, user A uses the app to send messages to user B. User B's app can receive messages, but the web end cannot receive messages (both OnRecvNewMessage and OnRecvNewMessages do not work). Reloading the message list also cannot obtain new messages. User B sends messages to user A using the app, but user A can receive messages. User B's web end cannot synchronize their messages, and user B sends messages to user A using the web end, User A's app can receive messages, and User B's app can also synchronize messages.

### What did you expect to happen?

Normal message exchange

### How can we reproduce it (as minimally and precisely as possible)?

In the same session, user A uses the app to send messages to user B. User B's app can receive messages, but the web end cannot receive messages (both OnRecvNewMessage and OnRecvNewMessages do not work). Reloading the message list also cannot obtain new messages. User B sends messages to user A using the app, but user A can receive messages. User B's web end cannot synchronize their messages, and user B sends messages to user A using the web end, User A's app can receive messages, and User B's app can also synchronize messages

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
You can use the web demo to test first to confirm that other links are normal.
