### ISSUE TITLE
Bug: <describe the error>IMSDK.createLocationMessage 方法调用失败，一直报参数异常

### ISSUE THREAD

**Issue by githubxiaobo** [openimsdk/open-im-sdk-web-wasm#70]
### What happened?

IMSDK.createLocationMessage 方法调用失败，一直报参数异常，参数传的都是正常的，如下图片，最新的 3.4.0版本，

![image](https://github.com/openimsdk/open-im-sdk-web-wasm/assets/16330155/02fbc9d8-c0de-4ba8-aa8d-16fa5d58889d)

![image](https://github.com/openimsdk/open-im-sdk-web-wasm/assets/16330155/29733a72-eec6-4a44-bda9-cd089a94a194)

### What did you expect to happen?

IMSDK.createLocationMessage 方法调用失败，一直报参数异常

### How can we reproduce it (as minimally and precisely as possible)?

创建IMSDK.createLocationMessage

![image](https://github.com/openimsdk/open-im-sdk-web-wasm/assets/16330155/02fbc9d8-c0de-4ba8-aa8d-16fa5d58889d)

### version

<details>
```console
$ {name} version
# paste output here
```
</details>
最新的 3.4.0版本

### Cloud provider

<details>
</details>
最新的 3.4.0版本

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
fixed
