### ISSUE TITLE
Bug: <createSoundMessage fail>

### ISSUE THREAD

**Issue by yoyoyo-wzw** [openimsdk/open-im-sdk-web-wasm#71]
### What happened?

"open-im-sdk-wasm": "^3.1.0", now using 3.1.0, image, video can create messages, voice messages fail.

Then just after replacing 3.4.0 with the new openim.wasm file. Images, videos, and voice messages failed to create

### What did you expect to happen?

Message created successfully

### How can we reproduce it (as minimally and precisely as possible)?

IMSDK.createSoundMessageByFile()

### version

"open-im-sdk-wasm": "^3.1.0"

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
Has it been resolved? Please confirm whether the parameters are correct
