### ISSUE TITLE
uniapp

### ISSUE THREAD

**Issue by mnz12138** [openimsdk/open-im-sdk-web-wasm#72]
### Description

uniapp fails to log in using web sdk, TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

**Comment by Bloomingg** [comment]
`open-im-sdk-wasm` only supports the vue3 version of unaipp to run on the h5 platform. If you need to allow it on multiple platforms such as vue2 or small programs, please use `open-im-sdk`. For details, please refer to the documentation: https://docs.openim.io/zh-hans/sdks/quickstart/uniapp
