### ISSUE TITLE
How to import open-im-sdk-wasm in webpack4.x

### ISSUE THREAD

**Issue by unicycle-master** [openimsdk/open-im-sdk-web-wasm#73]
### What would you like to share?

How to use openIM3. x without upgrading to webpack5, the webpack ^ 4.4.2 used in Vue2

**Comment by Bloomingg** [comment]
1. add patch-package
```bash
npm i patch-package
```
2. update package.josn scripts
```json
"scripts": {
+  "postinstall": "patch-package"
 }
```
3. update open-im-sdk-wasm
> node_modules->open-im-sdk-wasm->lib->index.js(index.es.js)
```js
function initWorker() {
    if (typeof window === 'undefined') {
        return;
    }
    // use for webpack 4
    const IMWorker = require('worker-loader!./worker.js');
    worker = new IMWorker.default();
    // use for webpack5+ or vite
    // const isViteEnvironment = import.meta.url.includes('.vite/deps');
    // const isSupportModuleWorker = supportsModuleWorkers();
    // const getWorkerUrl = (url) => url.href.replace('.vite/deps', 'open-im-sdk-wasm/lib');
    // const workerUrl = isSupportModuleWorker
    //     ? new URL('worker.js', import.meta.url)
    //     : new URL('worker-legacy.js', import.meta.url);
    // worker = new Worker(isViteEnvironment ? getWorkerUrl(workerUrl) : workerUrl, {
    //     type: isSupportModuleWorker ? 'module' : 'classic',
    // });
    // This is only required because Safari doesn't support nested
    // workers. This installs a handler that will proxy creating web
    // workers through the main thread
    initBackend(worker);
    rpc = new RPC({
        event: new RPCMessageEvent({
            currentEndpoint: worker,
            targetEndpoint: worker,
        }),
    });
}
```
4. patch change
```bash
npx patch-package open-im-sdk-wasm
```
5. add web worker loader
```bash
npm i worker-loader worker-plugin -D
```
6. update webpack config
```js
const WorkerPlugin = require("worker-plugin");

...
plugins: [new WorkerPlugin()]
...
```
7. import and use
```js
import { getSDK } from 'open-im-sdk-wasm';

const IMSDK = getSDK();
```

**Comment by 15949634581** [comment]
![企业微信截图_17228262975782](https://github.com/user-attachments/assets/eb744c23-8031-45c0-9860-e6ce5174fcf4)
按照上面执行完之后报这个异常怎么解决，之前也出现过但过了一天自己就好了，这次更新了一下sdk又有这个问题了

**Comment by Bloomingg** [comment]
> ![企业微信截图_17228262975782](https://private-user-images.githubusercontent.com/115760854/355034260-eb744c23-8031-45c0-9860-e6ce5174fcf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTQzNzQsIm5iZiI6MTcyMzAxNDA3NCwicGF0aCI6Ii8xMTU3NjA4NTQvMzU1MDM0MjYwLWViNzQ0YzIzLTgwMzEtNDVjMC05ODYwLWU2Y2U1MTc0ZmNmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwNzAxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2EyOTk4NjEwMjhiZWRjNDk3MGQ5MTk1YzFiZjNjZTNlZmQzZTUzYTk4ZTI4ZmFhNDgxZGM1Y2ViZWM1NDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ef4Shn27FwKZ4_hSCUZm9eKd_KZxQMNYSLwKSnuP5Ik) 按照上面执行完之后报这个异常怎么解决，之前也出现过但过了一天自己就好了，这次更新了一下sdk又有这个问题了

It looks like it failed when calling the cache API. You can raise a separate issue to discuss this issue.
