### ISSUE TITLE
How to remove the sdk console

### ISSUE THREAD

**Issue by TuCTu** [openimsdk/open-im-sdk-web-wasm#74]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

Too much printing inside the sdk

### Solution Description

Make a configuration to remove these prints, or make a version without prints

### Benefits

People who don't need these prints

**Comment by Bloomingg** [comment]
added in this [commit](https://github.com/openimsdk/open-im-sdk-web-wasm/commit/ad2d9ec5d500021560ccf8091bb7d68d5b5fb19d), and release open-im-sdk-wasm@3.5.1-alpha.8.1.
