### ISSUE TITLE
Bug: 浏览器 sdk 获取用户好友api的返回类型存在错误和文档不一致

### ISSUE THREAD

**Issue by aurora-engine-org** [openimsdk/open-im-sdk-web-wasm#76]
### What happened?

使用 v3.5.0 时候的 getFriendList api 发现返沪类型不一致

### What did you expect to happen?

希望修复和文档保持一致

### How can we reproduce it (as minimally and precisely as possible)?

![微信截图_20240205194021](https://github.com/openimsdk/open-im-sdk-web-wasm/assets/58322844/5bb9c68c-d073-42b9-9f47-96aab15fa7d6)

### version

<details>
v3.5.0
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
Windows 11
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
you can update the latest version
