### ISSUE TITLE
nuxt2 with open-im-sdk-web-wasm

### ISSUE THREAD

**Issue by StupidcCow** [openimsdk/open-im-sdk-web-wasm#77]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

✅ Yes

### Problem Description

![图片](https://github.com/openimsdk/open-im-sdk-web-wasm/assets/18227321/0890eef2-215d-4606-b243-a0affca6202e)
nuxt2 init sdk has error.

### Solution Description

hope to solution

### Benefits

hope to solution

**Comment by Bloomingg** [comment]
support in open-im-sdk-wasm@3.5.3-alpha.4
