### ISSUE TITLE
Bug: Upgrading browser SDK client open-im-sdk-wasm@3.5.1-alpha.8.1 Mark read messages in the future and send errors

### ISSUE THREAD

**Issue by jimu-os** [openimsdk/open-im-sdk-web-wasm#78]
### What happened?

Upgrade browser SDK from v3.5.0 to open-im-sdk-wasm@3.5.1-alpha.8.1 The normal login system retrieved the message session list. When loading the message, an error occurred when calling to mark the current message as read. The previous v3.5.0 version was normal (single chat session)
![微信截图_20240220155003](https://github.com/openimsdk/open-im-sdk-web-wasm/assets/58322844/f26d8af3-388d-4eb5-89e0-9d141cd368d7)

### What did you expect to happen?

The previous version had no problem with duplicate tags, and after calling the message tag, it should run normally (single chat session)

### How can we reproduce it (as minimally and precisely as possible)?

At present, it is caused by the upgrade version of the SDK on the browser side. I am not sure if it is related to the IM service version on the backend, which is release v3.5

### version

<details>
```console
Browser sdk @ Sunqinying 3.5.1-alpha.8.1
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
you can clear you indexdb and try again.
