### ISSUE TITLE
openIM.wasm文件加载时间过长解决方案

### ISSUE THREAD

**Issue by thydself** [openimsdk/open-im-sdk-web-wasm#82]
### What would you like to share?

未加cdn
<img width="976" alt="image" src="https://github.com/openimsdk/open-im-sdk-web-wasm/assets/38156359/a2406583-5990-4a44-8ca1-d90a7ca18225">
加了cdn之后
<img width="972" alt="image" src="https://github.com/openimsdk/open-im-sdk-web-wasm/assets/38156359/6c06af44-0cd2-4b07-be7b-7b07e53a99c9">

代码引入cdn 的位置：
<img width="253" alt="image" src="https://github.com/openimsdk/open-im-sdk-web-wasm/assets/38156359/47988f13-b3de-441d-8716-5fae67a6bc20">

getSDK的时候加入2个path 参数，填你cdn的path就好了

**Comment by cipchk** [comment]
CDN 会引发 CORS，哪怕是同域的情况下并且启用相关的 `Access-Control-Allow`。

**Comment by Bloomingg** [comment]
> CDN 会引发 CORS，哪怕是同域的情况下并且启用相关的 `Access-Control-Allow`。

You need to consult the CDN service provider you use.
