### ISSUE TITLE
[BUG] After removing a group member through the RESTful interface, the client (sdk) was not updated correctly.

### ISSUE THREAD

**Issue by onlyGuo** [openimsdk/open-im-sdk-web-wasm#90]
### OpenIM Server Version

3.7

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

 通过Restful接口移除群成员后, 客户端未正确更新，此时再通过Restful新增这个成员时，客户端报错如下：
```
worker.js:1  Error: UNIQUE constraint failed: local_group_members.group_id, local_group_members.user_id
    at r.handleError (worker.js:1:93457)
    at e.step (worker.js:1:88821)
    at r.exec (worker.js:1:92279)
    at worker.js:1:222438
    at worker.js:1:222446
```

**Comment by Bloomingg** [comment]
You can try to use the latest version of SDK and server
