### ISSUE TITLE
[BUG]  After introducing dsbridge, session list data accumulates abnormally during account switching

### ISSUE THREAD

**Issue by zmm4900** [openimsdk/open-im-sdk-web-wasm#91]
### OpenIM Server Version

3.5.1-alpha.6

### Operating System and CPU Architecture

macOS (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1、await IMSDK.getConversationListSplit 获取的会话列表数据异常，有上一个账号的数据。
2、通过排查定位到，当不引入dsbridge时，会话列表数据获取正常。
3、排查加载顺序，wasm版本sdk先引入，dsbridge后引入。
4、观察wasm版本sdk和dsbridge的window对象挂在的方法，发现都有close方法，而后引入的dsbridge对象覆盖了sdk的close方法。
5、猜测sdk的close方法不能正常执行，导致账号切换时会话列表数据出现异常累加。

**Comment by Bloomingg** [comment]
You can try to change the mount method of dsbridge to another name
